Repository KonduitAI/konduit-serving, pull requests merged in 2019-12, with the labels that each got.

#127 Fixed issue for konduit cli failing on windows for the `build` command
  build_jar.py
Labels: bug

#130 build_jar.py fixes
  build_jar.py
Labels: bug

#163 Removing extra dimension from nd4j input adapter
  konduit-serving-core/src/main/java/ai/konduit/serving/pipeline/handlers/converter/multi/converter/impl/nd4j/VertxBufferNd4jInputAdapter.java
Labels: bug

#122 Version upgrades to fix gpu build
  build_jar.py
  konduit-serving-gpu/pom.xml
  konduit-serving-gpu/src/main/java/ai/konduit/serving/gpu/GpuMetrics.java
  konduit-serving-test/file.json
  pom.xml
Labels: WIP

#176 Adding server event hooks
  konduit-serving-core/src/main/java/ai/konduit/serving/configprovider/KonduitServingMain.java
  konduit-serving-core/src/main/java/ai/konduit/serving/configprovider/KonduitServingMainArgs.java
  konduit-serving-test/src/test/java/ai/konduit/serving/configprovider/KonduitServingMainTest.java
Labels: enhancement

#161 Updating version to 0.1.0-SNAPSHOT and generating artifacts for konduit (TAR/DEB/RPM)
  .gitignore
  konduit-serving-api/pom.xml
  konduit-serving-codegen/pom.xml
  konduit-serving-converter/pom.xml
  konduit-serving-core/pom.xml
  konduit-serving-core/src/main/java/ai/konduit/serving/configprovider/KonduitServingNodeConfigurer.java
  konduit-serving-core/src/main/java/ai/konduit/serving/configprovider/MemMapRouteDefiner.java
  konduit-serving-deb/pom.xml
  konduit-serving-deb/src/deb/control/control
  konduit-serving-deb/src/deb/control/postinst
  konduit-serving-deb/src/deb/control/preinst
  konduit-serving-deb/src/deb/control/prerm
  konduit-serving-deb/src/main/resources/etc/konduit/serving/logback.xml
  konduit-serving-deb/src/main/resources/etc/pipelines/pipelines-env.sh
  konduit-serving-deb/src/main/resources/etc/pipelines/publickey.txt
  konduit-serving-deb/src/main/resources/etc/profile.d/konduit-serving-env.sh
  konduit-serving-deb/src/main/resources/etc/profile.d/pipelines-env.sh
  konduit-serving-deb/src/main/resources/scripts/pre-start.sh
  konduit-serving-deb/src/main/resources/systemd/pipelines.service
  konduit-serving-deb/src/main/resources/templates/konduit-serving-env.sh.template
  konduit-serving-distro-bom/pom.xml
  konduit-serving-docker/pom.xml
  konduit-serving-exe/pom.xml
  konduit-serving-gpu/pom.xml
  konduit-serving-native/pom.xml
  konduit-serving-orchestration/pom.xml
  konduit-serving-orchestration/src/main/java/ai/konduit/serving/orchestration/KonduitOrchestrationMain.java
  konduit-serving-pmml/pom.xml
  konduit-serving-python/pom.xml
  konduit-serving-rpm/pom.xml
  konduit-serving-rpm/src/main/resources/etc/konduit/serving/logback.xml
  konduit-serving-rpm/src/main/resources/etc/pipelines/pipelines-env.sh
  konduit-serving-rpm/src/main/resources/etc/profile.d/konduit-serving-env.sh
  konduit-serving-rpm/src/main/resources/etc/profile.d/pipelines-env.sh
  konduit-serving-rpm/src/main/resources/scripts/post-install.sh
  konduit-serving-rpm/src/main/resources/scripts/post-trans.sh
  konduit-serving-rpm/src/main/resources/scripts/pre-install.sh
  konduit-serving-rpm/src/main/resources/scripts/pre-remove.sh
  konduit-serving-rpm/src/main/resources/scripts/pre-start.sh
  konduit-serving-rpm/src/main/resources/scripts/pre-trans.sh
  konduit-serving-rpm/src/main/resources/systemd/pipelines.service
  konduit-serving-rpm/src/main/resources/templates/konduit-serving-env.sh.template
  konduit-serving-tar/README.md
  konduit-serving-tar/pom.xml
  konduit-serving-tar/src/main/assembly/assembly.xml
  konduit-serving-tar/src/main/resources/bin/konduit-serving
  konduit-serving-tar/src/main/resources/scripts/install-python.sh
  konduit-serving-test/pom.xml
  konduit-serving-test/src/main/java/ai/konduit/serving/verticles/BaseVerticleTest.java
  konduit-serving-test/src/test/java/ai/konduit/serving/executioner/inference/TensorflowInferenceExecutionerTests.java
  konduit-serving-test/src/test/java/ai/konduit/serving/orchestration/KonduitOrchestrationMainTest.java
  konduit-serving-uberjar/pom.xml
  konduit-serving-war/pom.xml
  pom.xml
  update-konduit-version.sh
Labels: WIP

#188 Don't force input_name in .step() method to default
  python/konduit/inference.py
Labels: Python
