Repository KonduitAI/konduit-serving, pull requests merged in 2020-03, with the labels that each got.

#261 Making Konduit-serving architecture more in sync with vertx
  konduit-serving-api/src/main/java/ai/konduit/serving/verticles/base/BaseRoutableVerticle.java
  konduit-serving-converter/src/main/java/ai/konduit/serving/input/converter/ConverterVerticle.java
  konduit-serving-core/src/main/java/ai/konduit/serving/configprovider/KonduitServingMain.java
  konduit-serving-core/src/main/java/ai/konduit/serving/verticles/inference/InferenceVerticle.java
  konduit-serving-orchestration/src/main/java/ai/konduit/serving/orchestration/ClusteredInferenceVerticle.java
  konduit-serving-orchestration/src/main/java/ai/konduit/serving/orchestration/KonduitOrchestrationMain.java
  konduit-serving-test/src/test/java/ai/konduit/serving/config/ConfigJsonCoverageTrackingTests.java
  konduit-serving-test/src/test/java/ai/konduit/serving/configprovider/KonduitServingMainTest.java
  konduit-serving-test/src/test/java/ai/konduit/serving/executioner/PipelineExecutionerTests.java
  konduit-serving-test/src/test/java/ai/konduit/serving/input/arrow/BatchInputArrowParserVerticle.java
  konduit-serving-test/src/test/java/ai/konduit/serving/input/arrow/BatchInputParserMultiRecordTest.java
  konduit-serving-test/src/test/java/ai/konduit/serving/input/image/BatchInputParserVerticle.java
  konduit-serving-test/src/test/java/ai/konduit/serving/input/nd4j/BatchNd4jInputParserVerticle.java
  konduit-serving-test/src/test/java/ai/konduit/serving/input/numpy/BatchNumpyInputParserVerticle.java
  konduit-serving-test/src/test/java/ai/konduit/serving/orchestration/KonduitOrchestrationMainTest.java
  konduit-serving-test/src/test/java/ai/konduit/serving/util/PortsTest.java
  konduit-serving-test/src/test/java/ai/konduit/serving/verticles/BaseVerticleTest.java
  pom.xml
Labels: cleanup

#262 Add jacoco config to collect coverage metrics add OWASP dependecy-check plugin and config
  Jenkinsfile
  pom.xml
Labels: enhancement

#256 Logging endpoints and tests
  konduit-serving-api/src/main/java/ai/konduit/serving/config/ServingConfig.java
  konduit-serving-codegen/src/main/java/ai/konduit/serving/codegen/pythoncodegen/CodeGen.java
  konduit-serving-core/pom.xml
  konduit-serving-core/src/main/java/ai/konduit/serving/configprovider/KonduitServingMain.java
  konduit-serving-core/src/main/java/ai/konduit/serving/configprovider/KonduitServingNodeConfigurer.java
  konduit-serving-core/src/main/java/ai/konduit/serving/configprovider/PipelineRouteDefiner.java
  konduit-serving-core/src/main/java/ai/konduit/serving/model/loader/ModelGuesser.java
  konduit-serving-core/src/main/java/ai/konduit/serving/util/LogUtils.java
  konduit-serving-core/src/main/resources/web/logs_page.html
  konduit-serving-python/src/main/java/ai/konduit/serving/pipeline/steps/PythonStepRunner.java
  konduit-serving-test/pom.xml
  konduit-serving-test/src/main/java/ai/konduit/serving/train/TestConfig.java
  konduit-serving-test/src/main/java/ai/konduit/serving/train/TestUtils.java
  konduit-serving-test/src/test/java/ai/konduit/serving/configprovider/KonduitServingMainTest.java
  konduit-serving-test/src/test/java/ai/konduit/serving/logs/LogsEndpointTest.java
  konduit-serving-test/src/test/java/ai/konduit/serving/orchestration/KonduitOrchestrationMainTest.java
  konduit-serving-test/src/test/java/ai/konduit/serving/util/PortsTest.java
  konduit-serving-test/src/test/resources/logback.xml
  konduit-serving-uberjar/src/main/resources/logback.xml
  pom.xml
  python/konduit/server.py
  python/tests/test_bert_serving.py
Labels: enhancement

#277 Fixing tensorflow issues for tests
  konduit-serving-api/src/main/java/ai/konduit/serving/util/SchemaTypeUtils.java
  konduit-serving-tfjava/pom.xml
  pom.xml
Labels: bug, dependencies

#280 Fixing JSON configuration errors from minimized yaml config
  build_jar.py
  konduit-serving-api/src/main/java/ai/konduit/serving/model/ModelConfig.java
  konduit-serving-api/src/test/resources/logback.xml
  konduit-serving-codegen/src/main/java/ai/konduit/serving/codegen/pythoncodegen/CodeGen.java
  konduit-serving-core/src/main/java/ai/konduit/serving/configprovider/KonduitServingMain.java
  konduit-serving-core/src/main/java/ai/konduit/serving/configprovider/PipelineRouteDefiner.java
  konduit-serving-deb/src/main/resources/etc/konduit/serving/logback.xml
  konduit-serving-docker/pom.xml
  konduit-serving-pmml/src/test/resources/logback.xml
  konduit-serving-rpm/src/main/resources/etc/konduit/serving/logback.xml
  konduit-serving-war/src/main/resources/logback.xml
  python/konduit/base_inference.py
  python/konduit/client.py
  python/konduit/load.py
Labels: bug
